[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
[bumpver]
current_version = "1.5.2"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver:file_patterns]
setup.py
    version="{version}",$
src/mymodule/__init__.py
    ^__version__ = "{version}"$